name: نیا مضمون
description: مطالعہ کے لیے نیا مضمون تیار کریں
title: "[مضمون] "
labels: ["publish"]
body:
  - type: dropdown
    id: category
    attributes:
      label: 📂 کٹیگری منتخب کریں
      description: مضمون شائع کرنے سے پہلے اس کی مناسب کٹیگری منتخب کریں۔
      options:
        - عقیدۂ توحید
        - تاریخِ اسلام
        - مشاجراتِ صحابہ
        - فرق و مذاہب
        - حدیث و آثار
        - کتبِ اسلامیہ
        - سیرت النبی ﷺ
        - سیرتِ صحابہ و تابعین
        - حالاتِ حاضرہ
    validations:
      required: true
  - type: input
    id: subject
    attributes:
      label: 📝 مضمون کا عنوان
      description: مضمون کا عنوان یہاں لکھیں۔
      placeholder: مثال: توحید کی اہمیت اور فضیلت
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: 📄 مضمون
      description: یہاں مکمل مضمون لکھیں۔
      placeholder: مکمل مضمون یہاں لکھیں...
      render: markdown
    validations:
      required: true
