backend:
  name: github
  repo: mutalaa92/mutalaa92.github.io
  branch: main

site_url: "https://mutalaa92.github.io"
display_url: "https://mutalaa92.github.io"

locale: "ur"
collections:
  - name: "posts"
    label: "مضامین"
    label_singular: "مضمون"
    folder: "_posts"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "عنوان"
        name: "title"
        widget: "string"

      - label: "زمرہ"
        name: "category"
        widget: "select"
        options:
          - "عقیدہ و توحید"
          - "حدیث و سنت"
          - "سیرت و تاریخ"
          - "علماء و ائمہ"
          - "کتب و تراجم"
          - "تحقیقی مقالات"
          - "ردِ باطل فرق و افکار"
          - "حالاتِ حاضرہ"
          - "منتخب تحریریں"

      - label: "نمایاں تصویر"
        name: "image"
        widget: "image"
        required: false

      - label: "اشاعت کی تاریخ"
        name: "date"
        widget: "datetime"
        required: true

      - label: "منتخب مضمون"
        name: "featured"
        widget: "boolean"
        default: false
        required: false

      - label: "ٹیگز"
        name: "tags"
        widget: "list"
        required: false

      - label: "مضمون"
        name: "body"
        widget: "richtext"
