backend:
  name: git-gateway
  branch: main

site_url: https://mutalaa.netlify.app
display_url: https://mutalaa.netlify.app

locale: ur

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: posts
    label: مضامین
    label_singular: مضمون
    folder: "_posts"
    create: true
    extension: md
    format: frontmatter

    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:

      - label: عنوان
        name: title
        widget: string

      - label: موضوع
        name: category
        widget: select
        options:

          - عقیدۂ توحید
          - تاریخِ اسلام
          - مشاجراتِ صحابہ
          - فرق و مذاہب
          - حدیث و آثار
          - کتبِ اسلامیہ
          - سیرت النبی ﷺ
          - سیرتِ صحابہ و تابعین
          - حالاتِ حاضرہ

      - label: تصویر
        name: image
        widget: image
        required: false

      - label: تاریخ
        name: date
        widget: datetime

      - label: نمایاں مضمون
        name: featured
        widget: boolean
        default: false
        required: false

      - label: ٹیگز
        name: tags
        widget: list
        required: false

      - label: مضمون
        name: body
        widget: markdown
